### ISSUE TITLE
[Question/Suggestion] Is there a simple way to remove an element without removing it from the DOM?

### ISSUE THREAD

**Issue by sebovzeoueb** [jsplumb/jsplumb#1000]
I'm making something using snabbdom and jsPlumb, and everything is working fine until I need to delete elements.

If I call instance.remove() in the snabbdom destroy hook, this causes the element to be deleted but snabbdom errors because it's still looking for it, and everything breaks.

What would be cool would be to be able to do all the stuff instance.remove() does without actually destroying the element, so I can let snabbdom deal with that. Is there a way to do this? If not, do you think it would be a nice feature?

**Comment by sporritt** [comment]
yes this might not be a bad idea.  I think in fact that what might be best is simply to change the default behaviour of `remove` to have it _not_ take the element out of the DOM, and add that option as a flag.

`remove` is a method that came about because in previous versions of jsPlumb there was a bunch of stuff attached to each managed element - listeners for clicks, listeners for drag, etc. Rather than make a user clean all that up when they wanted to take an element out of the DOM, jsPlumb offered a method. But in 4.x events are handled via a delegated handler on the container, and, endpoints/connections aside, you can "safely" remove an element without leaving behind any event listeners that will leak memory.

Perhaps even, in fact, what should happen is `unmanage` should remove endpoints/connections, and `remove` should be thrown away. This might be the most sensible option: unmanaging an element means you don't want jsPlumb to track it any more, so why would it still have endpoints/connections?

**Comment by sebovzeoueb** [comment]
Yes, I was actually surprised that `unmanage` didn't do that. I think `remove` is useful too though if you're just putting something together in plain JS.

I did actually manage to solve my problem in the end by deferring the removal to after the snabbdom cleanup, and also making sure to set a key on the vnodes to avoid the same element getting recycled with a different ID (in case anyone else is having issues with this).

Personally I would be in favour of keeping `remove` and making `unmanage` do all the cleanup without destroying the element.

**Comment by sporritt** [comment]
in `4.0.0-RC26` the `unmanage` method removes all endpoints/connections and optionally removes the element from the DOM:

```
unmanage (el:any|string, removeElement?:boolean):void
```

`remove` is no longer available.  I don't think that it's jsPlumb's responsibility to offer methods that are not related to its core purpose; anyone can write a method to remove an element from the DOM. `remove` was there in the first place out of necessity, because of the way previous versions of jsPlumb would attach a bunch of stuff to each element: if you didn't use `remove` then a whole load of loose ends were left over.

Having said that, there is currently a `removeElement` method available on `JsPlumbInstance`, which does remove elements from the DOM. It exists because the jsPlumb core is unaware of the the specifics of the renderer but needs a hook to advise the renderer to remove some element. So, you could use this, although it's not strictly part of the API, and may not always be available.

**Comment by sporritt** [comment]
closing this.
