### ISSUE TITLE
@jsplumb/browser-ui 4.0.0-RC37 source and target types

### ISSUE THREAD

**Issue by OriginalEXE** [jsplumb/jsplumb#1013]
Hello,

I am testing out the latest RC (thank you for your work) and I was wondering if maybe the types are wrong on the `source` and `target` properties of the `connect` method? Same for `revalidate`.

It seems like the types it expects are `jsPlumbElement | Endpoint | undefined`, but from your tests and my personal experimentation, it works when passing just `Element` instead?

Code that works:
```
plumbInstance.revalidate(
  document.getElementById('someId') as any,
)
```

Let me know if I'm missing something.

Thanks

**Comment by sporritt** [comment]
Yes I wondered if there'd be some feedback on this decision. In Javascript all of the methods that have `jsPlumbElement` as a method argument work by passing in a DOM element, yeah. The `jsPlumbElement` thing came about because of the .d.ts files that Typescript ships. The typings for their `Element` type do not reflect the reality of what browsers provide, or of what can be "done" to one, and so internally it has to be cast to something more useful. There is also no proper overlap in the type definitions between `SVGElement` and `HTMLElement`, either, despite the fact that in the real world there very much is. Even `EventTarget`, which is what you get from an `Event` doesn't have a usable overlap with the actual DOM elements you're going to treat them as.  I actually half finished a blog post about all that stuff and then decided I'd be better off spending my time working.

In your example you haven't passed in Element. You've passed in `any`. Can you not cast it to `jsPlumbElement` ? Although of course I can see why you might be reluctant.

**Comment by OriginalEXE** [comment]
Thanks for the detailed explanation 🙇🏻 

> I actually half finished a blog post about all that stuff and then decided I'd be better off spending my time working

I would be interested in reading this. Writing is also work :) If you remember, post the link to the post here if you ever get to finishing it.

> In your example you haven't passed in Element. You've passed in any

Yeah, what I meant is that padding a regular DOM element as returned by `getElementById ` works.

> Can you not cast it to jsPlumbElement ? Although of course I can see why you might be reluctant.

Nope, because it seems like `jsPlumbElement` has some additional attributes:
```
Conversion of type 'HTMLElement' to type 'jsPlumbElement' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'HTMLElement' is missing the following properties from type 'jsPlumbElement': _jsPlumbTargetDefinitions, _jsPlumbSourceDefinitions, _jsplumbid, _jsPlumbGroup, and 3 more
```

Perhaps one solution would be to make those additional attributes optional? I can see how that might require some code changes, but it might be more accurate (since those attributes might not be present on the element that is passed in)?

**Comment by sporritt** [comment]
In fact none of the properties on the `jsPlumbElement` interface are present on the element, because they are things jsPlumb wants to write.  It's actually a subclass, er, subinterface, whatever - `jsPlumbDOMElement` - used by the browser UI, which overrides certain things like `parentNode` to normalise them back into reality. I think in fact I'm just going to have to bite the bullet and do the casting inside jsPlumb.

**Comment by sporritt** [comment]
...although the other complication is that I don't want core to have to know about the DOM, since the plan is to support a headless version at some point.  I've messed around for ages with a type parameter that identifies what is actually being connected, but it's very leaky, to the point that I asked Typescript how they'd feel about supporting a neater syntax for these sorts of use cases:

https://github.com/microsoft/TypeScript/issues/42249

in the absence of which perhaps I ought to take the advice given in the first response and use generics to duct tape it together.

**Comment by OriginalEXE** [comment]
Understood. You're obviously well versed in TS so not sur I can offer any meaningful approach you didn't think of already. Let me know if I can help in any other way. The issue is not a deal breaker for me by any means, but it sure would be nice to find a way around it.

**Comment by sporritt** [comment]
@OriginalEXE Do you want to try 4.0.0-RC38, which has just been published?

**Comment by OriginalEXE** [comment]
Well that was fast :) I've just tried it out and it works, I was able to remove my type assertions and the methods "just work" with my `Element`s, thank you! I hope it did not complicate your life too much.

**Comment by sporritt** [comment]
No, its all good. I wasnt very happy with all those interfaces anyway. It's much better like this. Thanks for the feedback.
