### ISSUE TITLE
addSourceSelector and reattaching source endpoint issues

### ISSUE THREAD

**Issue by panayotisk** [jsplumb/jsplumb#1122]
**Version**: jsplumb 5.5.5
**Codepen**: https://codesandbox.io/s/addsourceselector-issues-012bv9

1st issue
**Summary**: When we reattach a source endpoint any source selectors declared after the first one seem to be ignored.
**Steps to reproduce**: In the given codepen create a connection from the left handler (the white square on the left) of the left element to the right element. After creating the connection detach the source endpoint and try to attach it to the right handler. The handler is ignored (the handler DOM element does not receive the class jtk-drag-hover at all).
**Notes**: When creating new connections the left handler and the right handler behave as expected. The problem can be seen when reattaching specifically the source endpoint of an existing connection. There seems to be no issue when reattaching the target endpoint of an existing connection to handlers.

2nd issue
**Summary**: When we reattach a source endpoint the endpoint options seem to be ignored.
**Steps to reproduce**: In the given codepen create a connection from the left handler (the white square on the left) of the left element to the right element. After creating the connection detach the source endpoint and try to attach it back to the left handler. This is doable. However, the connection is created from the bottom of the element instead of from the left.

Probably the two issues are related. This is the reason I report them together. I hope the information above is enough to understand the problems, if not please ask me to elaborate.

**Comment by sporritt** [comment]
The first issue here is caused by a poorly documented parameter on `addSourceSelector` / `addTargetSelector` - `redrop`.

https://docs.jsplumbtoolkit.com/community/apidocs/core.behaviouraltypedescriptor
https://docs.jsplumbtoolkit.com/community/apidocs/core.redrop_policy_strict
https://docs.jsplumbtoolkit.com/community/apidocs/core.redrop_policy_any

Theoretically, if you added `redrop:'any'` to your `addSourceSelector` call, then you'd be able to drop the source back anywhere onto the source element. In practice, though, if you do that in the codepen you can only drop on the element itself, not either of the `.child` elements. I don't know why this happens since in a unit test for this stuff the feature works as intended. I need to check this first.

The second issue is a bug.

Lastly, I have a feeling that even if `redrop:'any'` were working properly here it may not satisfy your use case entirely, as 'any' means anywhere on the element, whereas it seems here you want it to be "any defined source selector on the element". If that is the case it may be possible to add another policy, called `anySource` perhaps.

**Comment by panayotisk** [comment]
Yes, most probably a specific redrop policy that would allow redrop on this element's selectors only, would fit in my case. 
I would be extremely happy if you could support it.

**Comment by sporritt** [comment]
On _this element's_ selectors only, or on matching selectors on any element?

**Comment by panayotisk** [comment]
Yes you are right, any matching selectors on any element.

**Comment by sporritt** [comment]
fixed in 5.6.0, released yesterday

**Comment by panayotisk** [comment]
I have checked the version 5.6.2 and these issues are resolved. Thank you - I do believe it is much better now with the additional redrop functionality.
