### ISSUE TITLE
500 Error For Community Site Documentation

### ISSUE THREAD

**Issue by alexjoyner** [jsplumb/jsplumb#1165]
Got a 500 at the documentation link https://docs.jsplumbtoolkit.com/6.x/

![image](https://user-images.githubusercontent.com/7675099/236919147-c878495d-7a7d-4357-890b-f50f5be02b8c.png)

**Comment by alexjoyner** [comment]
Just found the docs from the gitub page, looks like the community site home page link needs to be updated to /community/6.x/ instead of just /6.x/

**Comment by sporritt** [comment]
Where did you find the link "https://docs.jsplumbtoolkit.com/6.x/"? I can't see such a link in the readme?

**Comment by MRERDUO** [comment]
Got a 500 at the documentation link https://docs.jsplumbtoolkit.com/community/2.x

**Comment by MRERDUO** [comment]
Where do I go to see the documentation for 2.x?

**Comment by j4acks0n** [comment]
> Got a 500 at the documentation link https://docs.jsplumbtoolkit.com/6.x/
> 
> ![image](https://user-images.githubusercontent.com/7675099/236919147-c878495d-7a7d-4357-890b-f50f5be02b8c.png)

I Think Its A Server Problem....

**Comment by sporritt** [comment]
Yes, I see it's a 500.  I'm not asking for an explanation of what a 500 error is.

The OP said "Got a 500 at the documentation link https://docs.jsplumbtoolkit.com/6.x/" and then "Just found the docs from the gitub page, looks like the community site home page link needs to be updated to /community/6.x/ instead of just /6.x/"

But in the repo's readme I cannot find that link.  So I am wondering where that link was found.

**Comment by LiJiaXv-NCU** [comment]
![image](https://github.com/jsplumb/jsplumb/assets/57059751/83c17eca-6106-4bda-9cfc-0ebec765c50c)
click this button, and you will find this link https://docs.jsplumbtoolkit.com/6.x/

**Comment by sporritt** [comment]
ok closing this. that's not helpful.

**Comment by sporritt** [comment]
...closed without seeing that red box. ok thanks. 

if anyone finds themselves here, docs are at https://docs.jsplumbtoolkit.com/community/6.x

**Comment by sporritt** [comment]
links updated.
