### ISSUE TITLE
Ability to drag labels

### ISSUE THREAD

**Issue by sporritt** [jsplumb/jsplumb#17]
From an original issue on google code: https://code.google.com/p/jsplumb/issues/detail?id=265

user would like the ability to drag labels along connector paths

**Comment by reebalazs** [comment]
Hi @sporrit!

I took a try on implementing this. https://github.com/reebalazs/jsPlumb/tree/ree-drag-labels-feasibility

Could you please have a look and see if this is in agreement with your plans?

The code is quite short and it's in its own file, https://github.com/reebalazs/jsPlumb/blob/ree-drag-labels-feasibility/src/draggable-labels.js . Apart from this, I did not need to change anything on the rest of the code. I wired it into the flowchart demo, where it can be tested.

I have however one particular issue that I cannot figure out. In my demo, each connection has an offset error, different from each other, but consistently the same even if I move the components. Sometimes this offset is close to zero but sometimes even 50px. I could not figure out where this is coming from. I am trying to use the offset of the connection's canvas to convert the x, y coordinates for findClosestPointOnPath. Apparently this is not good. The problem is probably not in findClosestPointOnPath, because it works perfectly apart from the offset, and I even implemented an alternate version of it with my own algorithm first, (for Straights only), which resulted in the exact same offset errors.

Perhaps you know what the problem can be? Thanks for your answer in advance.

**Comment by reebalazs** [comment]
I've fixed the offset issue. The problem was that I calculated the offset to be applied for the connection, from the connection's canvas. Instead, it has to be taken from the top-left bounds of the two connectors. The offset error occurred in the cases, when the connector's canvas is extended beyond the two connectors.

I'll need to clean this up a bit, but it's basically working, so now I will work towards a PR.

One question remains. Shall it remain a separate 'plugin', that one can activate in the following way:

```javascript
    // set up draggable labels
    jsPlumb.makeLabelsDraggable(instance);
```

or, shall it become builtin which means that all labels would implicitly become draggable?

**Comment by sporritt** [comment]
hi

I haven't had an opportunity to look at this yet, but it sounds cool.  a few questions:

- what happens when the user drags one of the elements? do the labels snap back to their automatically assigned positions?

- is there any facility to save/restore the custom label positions?

for now I'd prefer to keep this code as a "plugin".

**Comment by reebalazs** [comment]
Hi @sporritt,

- If the user drags an element or changes a connection, the position is kept. It seems like the 'loc' attribute is preserved during these operation, and it does not snap back.

- I have not made any facility to save-restore the positions. I will soon integrate this to a website where the model is currently saved, and as the label becomes draggable, its position will need to be saved as well. If anything special is needed to carry this out, then I would probably realize and develop it at that point. 

For the plugin question: ok, then it stays the way it is. In this case, demo-wise, shall it just stay in the flowchart demo? Or shall I make a separate demo for the draggable labels? (by copying the flowchart demo, for example).

**Comment by christopherreay** [comment]
(y)(y)
ᐧ

On 27 January 2015 at 19:32, Balázs Reé <notifications@github.com> wrote:

> Hi @sporritt <https://github.com/sporritt>,
>
>    -
>
>    If the user drags an element or changes a connection, the position is
>    kept. It seems like the 'loc' attribute is preserved during these
>    operation, and it does not snap back.
>    -
>
>    I have not made any facility to save-restore the positions. I will
>    soon integrate this to a website where the model is currently saved, and as
>    the label becomes draggable, its position will need to be saved as well. If
>    anything special is needed to carry this out, then I would probably realize
>    and develop it at that point.
>
> For the plugin question: ok, then it stays the way it is. In this case,
> demo-wise, shall it just stay in the flowchart demo? Or shall I make a
> separate demo for the draggable labels? (by copying the flowchart demo, for
> example).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sporritt/jsPlumb/issues/17#issuecomment-71711863>.
>



-- 

Be prepared to have your predictions come true

**Comment by AbuJunayd** [comment]
@reebalazs Thanks for the draggable plugin. I have downloaded it and initialized like you showed (jsPlumb.makeLabelsDraggable(instance);) but when I click on a label it instantly snaps on the source node, and I can't move it from there. It stays stucked.

I'm using dom.jsPlumb-1.7.2 - 

Any idea?

**Comment by AbuJunayd** [comment]
Ok, I found why. findClosestPointOnPath is only implement for straight connectors, and I was using Bezier connectors. It's working fine with straight ones.

**Comment by sporritt** [comment]
Closing this. It won't be something that gets added to the Community edition, but is available in the Toolkit.
