### ISSUE TITLE
printing

### ISSUE THREAD

**Issue by sporritt** [jsplumb/jsplumb#35]
placeholder to remind me to take a look at printing jsplumb stuff and create a wiki page for it.

**Comment by zeoc** [comment]
Like David, Been and Glavin I tried to mix HTML2Canvas, CanVG and canvasToBlob.
Success Here a very basic sample : 

	var el = $('.flow_container').get(0); // get flow container div
	html2canvas(el, {
        onrendered: function(canvas) {
			ctx = canvas.getContext('2d');
			// # Render Flows/connections on top of same canvas
			$flows = $('> svg', el);
			$flows.each( function() {
				$svg = $(this)
				offset = $svg.position();
				svgStr = this.outerHTML;
				ctx.drawSvg(svgStr, offset.left, offset.top);
			});
			// # Render Endpoints
			$endpoints = $('._jsPlumb_endpoint > svg', el);
			$endpoints.each(function() {
				$svg = $(this)
				offset = $svg.parent().position();
				svgStr = this.outerHTML;
				ctx.drawSvg(svgStr, offset.left, offset.top);
			});
			//# Convert canvas to Blob
			canvas.toBlob(function(blob) {
				//# Download Blob canvas
					NF.downloadData("test.jpg", blob, 'image/jpeg')
			});
		}
	});	

this is an jquery adapt from Glavin001 code.

**Comment by Glavin001** [comment]
Excellent! Great to hear it worked for you too, @zeoc.

**Comment by PhiLhoSoft** [comment]
[Highcharts](http://www.highcharts.com/demo/line-basic) allow to print out a chart or to export it to various formats (bitmap, SVG, etc.).
IIRC, they do so with server support, sending the chart settings (a Json file) to it, retrieving the rendering done with PhantomJS or similar.
They explain the process (so that users can implement it on their servers) in a page of their documentation.

Printing out a bitmap rendering has the risk of lowering the quality.

**Comment by fatemehgholampour** [comment]
@Glavin001 @zeoc that was great but it doesnt capture lable of connection

**Comment by sporritt** [comment]
I'm going to close this.  Nowadays I use headless chrome on the server to print.
