### ISSUE TITLE
Add delay property to the listener set by makeSource

### ISSUE THREAD

**Issue by mwielondek** [jsplumb/jsplumb#376]
The `mouseDownListener` which is binds to an element through `makeSource` prevents other mouse events from being recognized. It would be good to add a `delay` property (similar to [jQuery UI's draggable](http://api.jqueryui.com/draggable/#option-delay)) to prevent unwanted drags when clicking an element.

**Comment by sporritt** [comment]
There seem to be two topics here: one, that mousedown is consuming all events, and two, that clicks look like an aborted drag. Am I reading that correctly?

**Comment by miloszw** [comment]
One, mousedown seems indeed to be consuming all events. Two, once the previous point has been addressed, the `mousedown` event should preferably be recognized as a drag event only if no `mouseup` event has been dispatched within the time slot specified as `delay`, otherwise recognize it is a click.

To illustrate my point with an example, I want to make my entire div element a connection source, but I also want it to recognize a single click which carries a different function in my app.

**Comment by miloszw** [comment]
I was able to mimic the desired behaviour by appending the below code to the `mouseDownListener` function. Perhaps it makes it clearer what I mean.

```
var clickEvt = new MouseEvent('click', {
  'view': window,
  'bubbles': true,
  'cancelable': true
});
elInfo.el.dispatchEvent(clickEvt);
```

**Comment by sporritt** [comment]
this can be done now by binding to the `tap` event instead of click.
