### ISSUE TITLE
Connector positions not updated on scrollable container

### ISSUE THREAD

**Issue by urbanhusky** [jsplumb/jsPlumb#626]
I've got a scrollable (`overflow: auto`) container in a flexible (flexbox) layout. All the connected elements are also in a flexible layout.
Additionally, I've set up an event handler on the container `scroll` and `resize`which calls `jsPlumb.repaintEverything();`

The connectors are always rendered based on the top-/leftmost scrolling position instead of where the elements are actually positioned.

**Comment by urbanhusky** [comment]
Nevermind, the correct syntax to set the container when requesting an instance is:
`jsPlumb.getInstance({ Container: "containerdiv"});`. 

*I had written it as `container:`, i.e. lowercase*

Scrolling works fine now, except that the overflowing connectors are rendered outside the container (https://github.com/jsplumb/jsPlumb/issues/625)

**Comment by Badhumvee** [comment]
HI Urbanhusky,

I have the same exact problem.  Scrollable (overflow:auto) container in a flexbox layout.  The connected divs are inside this container.  The arrows are drawing correct for the starting position when you first load the page, but when you scroll the container, the divs scroll away and the arrows are left in their original position.  

I got to a point where I am able to listen to the scrolling event 'scroll-event'  (because its logging in the console.log).   

```

      jsPlumb.setContainer("#all-layers");
-
-
-
-
  document.getElementById('container').addEventListener("scroll", function() {
    console.log("scrolling");
    jsPlumb.repaintEverything();      //  <---------This doesnt seem to actually move the connector to the child div's new position.  The console.logs before and after are both printing to the log.
    console.log("painted?");    
  }, true);
```

I am quite new to javascript, let alone jsplumb.  Would you be kind enough to please show a demo of how you made it work on jsfiddle or codepen?  Also, I cannot use jQuery, so it has to be javascript.  Thanks.

**Comment by urbanhusky** [comment]
I've ended up drawing my own connectors on an svg and used something similar to `watch-element-resize` to detect size changes (and trigger full redraw). It's not ideal as it gets quite slow the more connectors are drawn but it works for our purpose. We don't use jsPlumb any more.

**Comment by Badhumvee** [comment]
HI urbanhusky, Thanks for the prompt response.  Cheers!
