### ISSUE TITLE
svgAttributeMap.ns.xhtml value is correct ?

### ISSUE THREAD

**Issue by tierrarara** [jsplumb/jsPlumb#637]
Inner src file i found   var svgAttributeMap with the below property

```javascript
var svgAttributeMap = {
...
    ns = {
        svg: "http://www.w3.org/2000/svg",
        xhtml: "http://www.w3.org/1999/xhtml"
    },
...
```

if i try to create a image  from svg source generated by jsplumb with the next code:
```javascript
var editor = $("#chart-container").get(0)
var connectors = $(editor).find('svg')

var img = new Image()
img.onload = function () { console.log('image was loaded')}
img.onerror = function () {console.log('error on image');}
img.src = "data:image/svg+xml," + (new XMLSerializer()).serializeToString(connectors.get(0))
img.complete
```
the onerror event will be fire

if i change svg xmlns attribute  'http://www.w3.org/1999/xhtml'
for  'http://www.w3.org/2000/svg'

the Image object will be created correctly

i don´t know if this is a issue or only i need set a configuration fix on my javascript

**Comment by sporritt** [comment]
the jsplumb code you referenced has got nothing to do with your snippet that creates an Image.

**Comment by tierrarara** [comment]
Sorry for my english maybe i wrotte in a wrong way my point!

 only i try to change the svg attributes, after change manually the connectors svg attributes the example code work ok,  jsplumb no create a images, this is my custom example code for convert svg to a image.

Why in the jsplumb source code was used that svg atribute value ? i think the option that i try to expose here can be a better attribute value for svg connectors, that let me create a images from jsplumb workflow chart, otherwise not.  

I don't know what are the  w3c svg standard, maybe i need check that!

**Comment by sporritt** [comment]
Ok yes, in fact that XHTML namespace is used when creating an SVG element inside jsPlumb. And your Image's `src` attribute does not like the serialized SVG. I see.

That line of code has been like that since at least 2013, but I cannot see a reference for why the code uses the XHTML namespace instead of the SVG namespace. It smells like something that would have been due to IE9, but I cannot find a reference to any requirement like this anywhere either.

it is tempting to just switch to the SVG namespace and do a release. But although it's a simple change it is quite fundamental, so we'll need to run a whole load of browser tests on this to see if anything is affected negatively.

**Comment by tierrarara** [comment]
I tested the example code only in chrome  58.0.3029.110 (64-bit),

thanks for your attention and your patience!

**Comment by sporritt** [comment]
code switched to use svg namespace.
