### ISSUE TITLE
use minimum canvas width/height of 10px for connectors (was: stroke-width isn't honored when using cssClass)

### ISSUE THREAD

**Issue by GuyShaanan** [jsplumb/jsplumb#647]
Attached plnkr: http://plnkr.co/edit/1j4P0xKra4MbIxIKzc8B?p=preview

My connectors are defined as Flowchart: `Connector: ["Flowchart", {cornerRadius: 10, midpoint: .9}]`.

When settings a cssClass to a jtk-connector (in this example called 'edge') and setting stroke and stroke-width, the stroke-width doesn't affect straight (vertical) lines (lines with a curve seems to work OK).

When using paintStyle (like in the second example)- strokeWidth works.

![image](https://user-images.githubusercontent.com/7248108/27082632-3e9ac1a6-504e-11e7-9086-315174bb1350.png)

**Comment by sporritt** [comment]
the canvas for the straight line is only 1 pixel wide, and it's cropping the line:

![image](https://user-images.githubusercontent.com/262720/31299235-2e60dfb4-ab39-11e7-8ae4-b7e79bf7c9af.png)


changing the svg width to 3px makes it show how you want:

![image](https://user-images.githubusercontent.com/262720/31299219-1de3cd18-ab39-11e7-9266-40369defd181.png)

Since the stroke width is applied via css, jsPlumb's only option to know that would be to interrogate the styles, which is not something, for performance reasons, we want to be doing. it probably wouldnt hurt for us to just make the canvas a minimum width of 10 pixels or something, to cover situations like this. Most people don't use lines of anything near as thick as 10 pixels.

**Comment by sporritt** [comment]
renaming and targeting 2.6.3

**Comment by sporritt** [comment]
This was remedied via CSS overflow in the defaults stylesheet.
