### ISSUE TITLE
Draggable and Resizable lost track on square

### ISSUE THREAD

**Issue by gmunumel** [jsplumb/jsPlumb#664]
Hello there. I hope you are good. 

I have an issue with a draggable and resizable image. For the drag functionality I use `jsPlumb.draggable` and for resizable `.resizable` from jquery-ui.

The issue seems to be related to the version of the library. The following example is showing the issue using the version `2.2.9`.
[Example - not working](https://jsfiddle.net/n0dix/em5t1tkn/)

If I use the version `1.4.1` is working fine. I guess should be other higher versions that works properly. 

Thanks for the great work with the library.

**Comment by sporritt** [comment]
two things going on here. first is that since 1.4.1 the method you want to use in situations that you want to force the paint cycle is `revalidate`:

```
$("#item_right").resizable({
  alsoResize: '#dude',
  resize: function(event, ui) {
    jsPlumb.revalidate(ui.helper);
  },
  handles: "all"
});
```

second is that without a `filter` provided to the `draggable` call, the element starts dragging as you resize, which makes it all go weird:

```
jsPlumb.draggable("item_left", {
      filter:".ui-resizable-handle"
   });
```


https://jsfiddle.net/em5t1tkn/6/

![image](https://user-images.githubusercontent.com/262720/29067072-a2bc4360-7c74-11e7-9c08-b600788937c8.png)

**Comment by gmunumel** [comment]
Thank you so much mate. 👍
