### ISSUE TITLE
Determine which connection is detached

### ISSUE THREAD

**Issue by koosvanderkolk** [jsplumb/jsplumb#691]
We let users create a workflow with connections between elements. 

There a many-to-many relationship between connections and elements, so one element can have multiple connections connected to one connector.

If a user wants to detach a certain connection by dragging the connector, how to determine which connection is being detached if there are several? Current behaviour seems to be random...

**Comment by sporritt** [comment]
current behaviour is to take the first connection that is attached to some endpoint. there's a `connectorSelector` function on each Endpoint:

```
/**
         * returns a connection from the pool; used when dragging starts.  just gets the head of the array if it can.
         */
        this.connectorSelector = function () {
            var candidate = this.connections[0];
            if (candidate) {
                return candidate;
            }
            else {
                return (this.connections.length < this._jsPlumb.maxConnections) || this._jsPlumb.maxConnections === -1 ? null : candidate;
            }
        }
```

...which, upon inspection, has a pointless bunch of code in the second branch of the IF - it will return null from that branch whatever happens. so i will rewrite this method to:

```
        this.connectorSelector = function () {
            return this.connections[0];
        }
```

you could override this method on your Endpoints to do something specific for your use case. I've never put anything in jsPlumb to do this since when a user starts to drag there is no way to intercede and allow a user to select a connection: some piece of knowledge must have already been attained in order to make a decision, such as the notion that some connection is "selected" or whatever. This sort of stuff is app specific and not stuff about which jsPlumb has an opinion.

**Comment by koosvanderkolk** [comment]
Dear Simon,

Thanks a lot for your reply. 

In my code I now let all EndPoints go through the following function.

```javascript
   /**
     * Adds some useful functions to jsPlumb endpoint objects.
     *
     * @param {object} endpoint
     *   A jsPlumb Endpoint (https://jsplumbtoolkit.com/community/apidocs/classes/Endpoint.html).
     */
    function improveEndpointAPI(endpoint) {
      /**
       * Sets the selected connection for this endpoint.
       *
       * @param {object} connection
       *   A jsPlumb Connection (https://jsplumbtoolkit.com/community/apidocs/classes/Connection.html).
       */
      endpoint.setSelectedConnection = function (connection) {
        endpoint.selectedConnection = connection;
      };

      /**
       * Returns the selected connection
       *
       * @returns {object}
       *   A jsPlumb Connection (https://jsplumbtoolkit.com/community/apidocs/classes/Connection.html).
       */
      endpoint.getSelectedConnection = function () {
        return endpoint.selectedConnection;
      };

      /**
       * Returns the index of the selected connection.
       *
       * @returns {int}
       */
      endpoint.getSelectedConnectionIndex = function () {
        var index;
        var storedIndex = endpoint.connections.indexOf(endpoint.getSelectedConnection());
        index = storedIndex >= 0 ? storedIndex : 0;
        return index;
      };

      /**
       * Overwrites the default connector connectorSelector function.
       *
       * @returns {object}
       *   A jsPlumb Connection (https://jsplumbtoolkit.com/community/apidocs/classes/Connection.html).
       */
      endpoint.connectorSelector = function () {
        return endpoint.connections[endpoint.getSelectedConnectionIndex()];
      };
    }
```

Next I bind to the connection 'click' event:

```javascript
connection.setParameter('sourceEndpoint', sourceEndpoint);
connection.setParameter('targetEndpoint', targetEndpoint);
connection.bind('click', function () {
  this.getParameter('sourceEndpoint').setSelectedConnection(this);
  this.getParameter('targetEndpoint').setSelectedConnection(this);
}, connection);
```

This works as a charm, but feels kinda hacky, as I am not only adding functions to 'live' objects, but also overwriting an existing function.

**Comment by sporritt** [comment]
it does feel kind of hacky, yes, although that function was deliberately exposed to support being overridden. there are a couple of alternative approaches we could look at:

- support a `connectorSelector` function in the `addEndpoint` method
- support a `connectorSelector` function in the `jsPlumb.newInstance(...)` method.

i dont see these as exclusive, necessarily: in the event that each was in use, I'd expect the one passed in to `addEndpoint` to take precedence.

**Comment by koosvanderkolk** [comment]
Thanks for your reply! If these functions are exposed, I think it is save to also expose get-ers and set-ers for all exposed object variables. In this instance: the 'connections' property. My overriding functions should not want to know the exact names of these properties, as they might change.

**Comment by sporritt** [comment]
yeah i dont know, javascript is such a free for all. originally jsplumb was written with proper grown up data hiding, private variables scoped only to the class closure, getters setters etc. then people started talking about memory usage and i moved everything, or at least many things, to the object's prototypes. memory usage went down but nothing was sacred anymore, and there became very little point in having getters or setters. 

from my point of view, now, putting a getter/setter on a "class" which itself is just manipulating a public variable is basically a waste of memory. that could be partly because i cut javascript loose in my mind a long time ago, but it might also be correct. who knows?  you don't even need to get _two_ developers in a room for there to be a disagreement.
