### ISSUE TITLE
Wrong target div connected

### ISSUE THREAD

**Issue by PierreTrp** [jsplumb/jsplumb#713]
https://jsfiddle.net/yxguru8a/4/

As you can see in the js code, source is `list_2_elem_1` and target is `list_1_elem_3` but when rendering, source is `list_2_elem_1` (which is correct) but target is `list_2_elem_3` instead of `list_1_elem_3`

**Comment by sporritt** [comment]
it is highly unlikely that the target is `list_2_elem_3`; jsPlumb doesn't choose arbitrary elements to connect.  

the problem is that since you did not set a Container for jsPlumb there's no common element between the two nested lists, and the offset calculations get confused.

with a container set:

https://jsfiddle.net/yxguru8a/10/

![image](https://user-images.githubusercontent.com/262720/36254318-d3d194e4-129e-11e8-995f-c9fbe7c34d7e.png)


note that if you start scrolling these lists you might find yourself back on here asking other questions.
