### ISSUE TITLE
Request some "after connection" events and public API to set the connection layout.

### ISSUE THREAD

**Issue by kittypaw** [jsplumb/jsplumb#883]
When using the 'connection' event, this event is fired before the svg is ultimately rendered. Therefore, the exact svg path can't be obtained in the 'connection' event.

Also, is there any existing method to set/modify the connection layout, or any plan to add similar features in the future?

**Comment by sporritt** [comment]
there is no plan to add user specified routing in the community edition. this will, however, be released in the Toolkit edition quite soon.

**Comment by kittypaw** [comment]
OK, got it. Any comment about the first request?

**Comment by sporritt** [comment]
um, not really, no, i suppose i don't. getting access to the svg is kind of pointless for you anyway since jsplumb will just blast any changes you make whenever it feels like it. your best approach would be to build your own connector, using one of the existing connectors as a model.

**Comment by kittypaw** [comment]
I mean, there is no regular way to drag new connection from an existing connection, thus divide one connection into two branches, right? I tried to use the "proxy-node" method as the relay but turned out getting access to the svg is necessary. Yeah, maybe I should build my own connnector.

**Comment by sporritt** [comment]
if you have an endpoint that has one connection then it is considered "full", since the default maximum connections is 1. when you drag again from that endpoint it just detaches the current connection in that case. setting `maxConnections` to some other value changes this; a value of -1 means there is no limit. in that case when you drag a new connection from an endpoint that is already connected you get a new connection, which i think is what you want to do?

**Comment by kittypaw** [comment]
I'm afraid you misunderstood. What I actually want to do is make branches of one connection, like draw a circuit diagram.

**Comment by sporritt** [comment]
we can probably close this then, as this functionality is not supported and there's nothing on the horizon that would do this.
