### ISSUE TITLE
What's the best way to update the positions of endpoints and edges

### ISSUE THREAD

**Issue by ilovepumpkin** [jsplumb/jsplumb#928]
Hi, I am working on a requirement to layout my graph in different methods, like vertical or horizontal. So basically I need to recalculate my node positions. Currently I recreate all endpoints and edges after re-positioning my nodes, but this way is really time consuming when there are many nodes and edges.  Is there any cheaper method to achieve this? My understanding is that JsPlumb already have all endpoints and edges managed, just need recalculate their positions(x and y) based on updated node positions. Is there any API to do this?

**Comment by ilovepumpkin** [comment]
oh, I guess I found the answer by myself - repaintEverything seems working.

**Comment by ilovepumpkin** [comment]
Well, I guess repaintEverything might not be the right answer. It is faster than recreating endpoints and edges, but after it is done and I drag nodes, the endpoint positions are messy. It looks like the issue https://github.com/jsplumb/jsplumb/issues/880, but I am not sure if they are same issue. 

So, I reopened this issue and looking forward the right answer.

**Comment by sporritt** [comment]
`repaintEverything` is probably what you need. what do you mean by "endpoint positions are messy" ?

**Comment by ilovepumpkin** [comment]
Thanks for your reply! Sorry that I should have described "endpoint positions are messy"  more clearly - I mean after I run repaintEverything and drag any node, the endpoints belonging to that node are not moving accordingly anymore, which stay at their original positions. But probably it is my own issue if others don't see this.

**Comment by akreienbring** [comment]
I have a similar need and solved it..., let't say by recalculating the difference of the endpoint positions and then adjusting the anchor position. I need to do that because I zoom the HTML elements. I zoom every single element and not the whole canvas. When the elements are not zoomed "repaintEverything" does a good job. If you like have a look in my [zoomit.js](https://github.com/akreienbring/dbdesigner/blob/master/src/js/zoomit.js) to see how I did it.

However, that may not the best way to do it and some kind of API function to achieve the same would clearly be helpful. 

BTW: The whole thing is necessary because the endpoints are added on the canvas. So they are not part of the HTML element that I zoom...

**Comment by sporritt** [comment]
@akreienbring you zoom each individual element?  what's the reason for that?

**Comment by akreienbring** [comment]
Due to the structure of the HTML Page. It has a header and the container DIV. I wanted the container to be scrollable in horizontal and vertical direction with a fixed size. This way, there's enough space for lots of elements. Simply zooming the container and telling jsplumb about the zoomfactor destroyed this structure and I could not find any css trick to maintain it.

So basically we're talking about css transformation of HTML elements with attached anchors. The applied css transformation is not taken into account by jsplumb with "repaintEverything".

**Comment by sporritt** [comment]
Something about this doesn't quite ring...without seeing a picture of how the structure was  "destroyed" it's difficult to comment, but I wonder if you remembered to not only set the zoom but also the `transform-origin`? The default `transform-origin` is the center of the element. Perhaps in your case

```
transform-origin: top left;
```

might help.
